language: python
python:
  - "3.2"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: echo "hello world install"
# command to run tests, e.g. python setup.py test
script:  echo "hello world script"
